xyflow/web

- sites/reactflow.dev/src/pages/_meta.json
- sites/reactflow.dev/src/pages/whats-new.mdx
- sites/reactflow.dev/theme.config.tsx
Adding a page to docs as a reference for long-time users of the React Flow docs to know what changed
> feat(whatsnew): Add "what's new" page to docs 

- apps/svelte-examples/src/routes/examples/feature-overview/+page.svelte
> fix(svelte-examples) use higher css specificity for global classes

- sites/reactflow.dev/src/pages/learn/advanced-use/state-management.mdx
Install command for Zustand was inverted
> typo: pnpm and yarn instructions were inverted

- apps/svelte-examples/src/routes/examples/nodes/easy-connect/CustomNode.svelte
Fixes a bug from [porting](https://github.com/xyflow/web/pull/67) over the React examples. The node labels were not updated when you started to drag a new connection out.
| Before | After |
| ------ | ----- |
| ![image](https://github.com/xyflow/web/assets/16587643/a9fc722c-6a06-4753-a932-58c421f86365) | ![image](https://github.com/xyflow/web/assets/16587643/33345343-ef43-4487-ad94-882d0446b56f) |
> fix(svelte-examples) Make easy-connect label reactive

- sites/reactflow.dev/src/page-data/reference/types/Edge.fields.ts
I don't know if this field was deprecated or removed or other. When I try to use this field in my project, there is no "selectable" field on a `FlowEdge`.
The codebase also mentions "selectable" in a few other places, so if this change is valid, I don't know if other places need to be updated as well.
> Removing "selectable" field from Edge API docs

- sites/reactflow.dev/src/components/example-viewer/example-flows/AddNodeOnEdgeDrop/index.js
The [Add Node On Edge Drop example](https://reactflow.dev/examples/nodes/add-node-on-edge-drop) does not respect the offset/bufferzone when connecting to existing nodes.
Fixed by resetting the ref to the started node when a full connect happens, this now supports offsetting handles, where the user doesn't need be directly on a handle to connect, where thus the cursor is detected as "on the pane".
Error in demo:
https://github.com/xyflow/web/assets/7737034/05cbd750-c8d3-4484-a6b2-1b113fa6efe3
Fixed version:
https://github.com/xyflow/web/assets/7737034/31330cdb-9559-437b-a0de-a089c5fc4ff2
> fix AddNodeOnEdgeDrop to support offset handles

- sites/reactflow.dev/src/components/example-viewer/example-flows/PreventConnectionCycles/index.js
Scope: "Preventing Cycles" example.
Issue:
With the current `isValidConnection` implementation it's still possible to cycle the node to itself.
This happens because `hasCycle` function assertions begin from the **outgoer** nodes only, skipping the initial one.
> Fix Preventing Cycles example node cycle itself

- sites/xyflow.com/src/sites/open-source.tsx
First paragraph on xyflow.com/open-source has been changed to include Pro Platform, and making the copy a little bit more clean.
> Add copy about open sourced Pro Platform to xyflow.com/open-source

- sites/reactflow.dev/src/pages/learn/customization/custom-edges.mdx
Typo in the code example for creating delete button in custom edge. The example shows setting new edges without the deleted one, but the function name is missing letter. setEdge(...) -> setEdges(...)
> Typo fix in docs, in Custom Edge section.

- sites/reactflow.dev/src/page-data/reference/ReactFlow.props.ts
- Add missing `onSelectionContextMenu` type reference to `ReactFlow.props.ts`
> chore(reactflow): add missing `onSelectionContextMenu` type reference

- sites/svelteflow.dev/src/pages/api-reference/components/background.mdx
Fixed typo in [background example](https://svelteflow.dev/api-reference/components/background) where color prop should be bgColor
> fixed typo on background example

- sites/reactflow.dev/src/pages/learn/layouting/layouting.mdx
The Layouting docs currently suggest that elkjs supports libavoid as an edge routing solution. While ELK (the Java version with all the docs) supports libavoid, it's not supported by elkjs (as of yet); see https://github.com/kieler/elkjs/issues/210.
This PR removes the link to elkjs and libavoid in the edge routing section since it can easily be confusing and take some time to figure out why libavoid isn't working with elkjs.
> fix(docs): remove suggestion of libavoid for edge routing

- pnpm-lock.yaml
- sites/reactflow.dev/src/components/example-viewer/example-flows/MultiConnectionLine/ConnectionLine.js
- sites/reactflow.dev/src/components/example-viewer/example-flows/MultiConnectionLine/index.js
- sites/reactflow.dev/src/pages/examples/edges/_meta.json
- sites/reactflow.dev/src/pages/examples/edges/multi-connection-line.mdx
- sites/reactflow.dev/src/pages/whats-new/2024-02-09.mdx
- sites/reactflow.dev/src/utils/routes.ts
Closes #315. We finally got round to cooking up an example! As always @bcakmakoglu contributed a non-trivial amount of the work ^.^
https://github.com/xyflow/web/assets/9001354/78a3d514-b980-4bce-9d39-18b40edfdd19
Not sure how I feel about importing and using `internalsSymbol` though...
> ✨ Add a guide for drawing multiple connection lines.

- sites/reactflow.dev/src/pages/learn/advanced-use/typescript.mdx
The page `sites/reactflow.dev/src/pages/learn/advanced-use/typescript.mdx` had a typo in the Usage with TypeScript section, the word TypeScript has been misspelled as `TypesSript`, this pull requests updates it to `TypeScript`.
> Fix "TypeScript" word typo in docs

- sites/svelteflow.dev/src/pages/learn/guides/custom-nodes.mdx
Fix incorrect reference of `TextUpdaterNode` to `ColorPickerNode`
> docs: Update documentation under the subheading "Adding a new node type"

- sites/reactflow.dev/src/pages/learn/advanced-use/typescript.mdx
When using the code shown on this page to kickstart a project, I noticed there were a couple of errors due to 'DefaultEdgeOptions' and 'NodeTypes' not having been imported.
Those imports are used in the following lines:
```
const defaultEdgeOptions: DefaultEdgeOptions = {
animated: true,
};
const nodeTypes: NodeTypes = {
custom: CustomNode,
};
```
This PR adds them so that issue no longer happen.
> Add missing imports to typescript.mdx

- sites/reactflow.dev/src/pages/api-reference/components/node-resize-control.mdx
- sites/svelteflow.dev/src/pages/api-reference/components/node-resize-control.mdx
It seem there are typos in `Reference > Component > NodeResizeControl` and it is marked on image below 
After checking xyflow repository NodeResizeControl component Type seems to be ResizeControlProps then I applied fix to both react and svelte
> Fixed typos in node-resize-control page

- sites/reactflow.dev/src/pages/learn/tutorials/mind-map-app-with-react-flow.mdx
**TL;DR**: Zustand warning `@deprecated — Use createWithEqualityFn from 'zustand/traditional'`
When following [ this example in the tutorial,](https://reactflow.dev/learn/tutorials/mind-map-app-with-react-flow#srcappindextsx-1) VSCode complains that this declaration using `create` is deprecated. 
Although the code works just fine, it recommends that we use `createWithEqualityFn` instead of `create`. It does solve the warning.
However, after some research, it seems that [Zustand might deprecate this `createWithEqualityFn`...](https://github.com/pmndrs/zustand/discussions/2243)
It seems that they initially had quite some confusions among the users, which lead to [v4.5.1 release fix](https://github.com/pmndrs/zustand/releases), but still using the zustand@latest did not fix this warning for …
> Use createWithEqualityFn in mind-map-app-with-react-flow.mdx

- sites/svelteflow.dev/src/pages/learn/guides/custom-nodes.mdx
This suppresses the warnings without needing to manually write out all of the individual props. You could also use `$$props` but I feel `$$restProps` makes more sense here.
> Replaced manual exporting of all props to use $$restProps instead

- sites/reactflow.dev/src/pages/api-reference/utils/get-outgoers.mdx
Fix typo and misleading variable name
> refactor: on `getOutgoers()` hook, change misleading variable and fix typos

- sites/reactflow.dev/src/components/example-viewer/example-flows/EntitreeFlexTree/CustomNode.js
- sites/reactflow.dev/src/components/example-viewer/example-flows/EntitreeFlexTree/index.js
- sites/reactflow.dev/src/components/example-viewer/example-flows/EntitreeFlexTree/nodes-edges.js
- sites/reactflow.dev/src/pages/examples/layout/_meta.json
- sites/reactflow.dev/src/pages/examples/layout/entitree-flex.mdx
This example shows how you can integrate [entitree-flex](https://github.com/codeledge/entitree-flex) with React Flow to create tree layouts that can have sibling nodes. Entitree flex also supports nodes with different dimensions.
https://d.pr/v/hZjhn4
> Examples: Add entitree-flex layout example

- sites/reactflow.dev/src/pages/api-reference/hooks/use-on-selection-change.mdx
The example provided for the useOnSelectionChange hook contained errors in the use of the useCallback hook. This commit addresses the following issues:
1. Added missing import statement for useCallback from 'react'.
2. Corrected the syntax of useCallback.
> fix: 🛠️ Correct useCallback usage in useOnSelectionChange example

- sites/svelteflow.dev/src/pages/api-reference/types/edge-marker.mdx
This is just a small pull request to fix a broken link.
Seems to be a simple error with the capital letter:
This works: https://svelteflow.dev/api-reference/types/edge
This doesn't: https://svelteflow.dev/api-reference/types/Edge
> Fixed a broken link in api-reference documentation

- sites/reactflow.dev/src/pages/learn/troubleshooting/index.mdx
Links useUpdateNodeInternals so that users seeing error 008 because they modified handles programmatically can easily fix their bug.
> Link useUpdateNodeInternals in error 008

- sites/svelteflow.dev/src/page-data/reference/SvelteFlow.ts
`selectionOnDrag` is present on [reactflow.dev](https://reactflow.dev/api-reference/react-flow#selection-on-drag), but is missing on [svelteflow.dev](https://svelteflow.dev/api-reference/svelte-flow#selection-on-drag).
Despite being missing from that page, the feature seems to be implemented.
I took the same definition from the [react page data](https://github.com/xyflow/web/blob/44b1c3ca8528680690f60aacabdcfadb0189dcfe/sites/reactflow.dev/src/page-data/reference/ReactFlow.props.ts#L501).
> Added missing documentation for `selectionOnDrag` property in svelteflow.dev

- apps/svelte-examples/src/routes/examples/nodes/update-node/+page.svelte
Changed `:gloabl` to `:global`
> chore(svelte-docs): fix typo

- sites/reactflow.dev/src/pages/learn/troubleshooting/migrate-to-v12.mdx
The old prop is referred to as "posX" rather than "xPos", ditto y.
> Corrected prop names in breaking changes "xPos/yPos"

- sites/reactflow.dev/src/pages/api-reference/utils/get-incomers.mdx
There is a minor typo in docs of `getIncomers`, here: https://reactflow.dev/api-reference/utils/get-incomers where the link for `getIncomers` formatted incorrectly.
This commit fixes a typo in the link for `getIncomers()`
> (docs): fix minor type in the link

- sites/reactflow.dev/src/components/example-viewer/api-flows/GettingStarted2/index.js
- sites/reactflow.dev/src/pages/learn/getting-started/building-a-flow.mdx
In the [Building a flow](https://reactflow.dev/learn/getting-started/building-a-flow#adding-nodes) page, the required `data` property is missing from the first example.
```diff
const nodes = [
{
id: '1', // required
position: { x: 0, y: 0 }, // required
+   data: { label: 'Hello' }, // required
},
];
```
> fix: data property is required in node objects

- apps/svelte-examples/src/routes/examples/interaction/drag-and-drop/+page.svelte
- apps/svelte-examples/src/routes/examples/interaction/drag-and-drop/DnDProvider.svelte
- apps/svelte-examples/src/routes/examples/interaction/drag-and-drop/Flow.svelte
- apps/svelte-examples/src/routes/examples/interaction/drag-and-drop/Sidebar.svelte
- apps/svelte-examples/src/routes/examples/interaction/drag-and-drop/utils.ts
- sites/reactflow.dev/src/components/example-viewer/example-flows/DragNDrop/DnDContext.jsx
- sites/reactflow.dev/src/components/example-viewer/example-flows/DragNDrop/Sidebar.jsx
- sites/reactflow.dev/src/components/example-viewer/example-flows/DragNDrop/index.jsx
- sites/reactflow.dev/src/pages/examples/interaction/drag-and-drop.mdx
- Use React/Svelte context to persist the dragged node type
- Use context value on drop of node
- Replace `dataTransfer` usages
- #465
> refactor(reactflow,svelteflow): use context to persist dragged node type

- sites/reactflow.dev/src/page-data/reference/types/ReactFlowInstance.fields.ts
- sites/svelteflow.dev/src/page-data/reference/hooks/useSvelteFlow.ts
- Add documentation for `getHandleConnections` to API-reference pages of `useReactFlow` & `useSvelteFlow`
Related to: https://github.com/xyflow/xyflow/pull/4574
> feat(reactflow,svelteflow): add documentation for `getHandleConnections`

- sites/svelteflow.dev/src/page-data/reference/types/Node.fields.ts
- Remove `positionAbsolute` from node field definitions as it's been removed from the user node type since v12
> fix(reactflow,svelteflow): remove `positionAbsolute` from node field definitions

- sites/svelteflow.dev/src/pages/api-reference/components/handle.mdx
Hey, I've been working with your package (which is awesome!) in svelte. I came to implementing a handle with a custom validator and found that the syntax seemed to follow react convention rather than svelte. I've tried to update it to svelte syntax.
> fix(custom-handle-example): update the custom handle example to svelte syntax

- sites/reactflow.dev/src/pages/learn/layouting/layouting.mdx
Noticed a couple of typos in the docs about Layouting, so figured I would fix them for ya.
> Fix a couple of typos in the layouting docs.

- sites/reactflow.dev/src/pages/learn/advanced-use/state-management.mdx
The word are was duplicated twice in the document and has been removed.
> Fix a duplicated word in the state management docs.

- sites/reactflow.dev/src/pages/api-reference/hooks/use-edges.mdx
- sites/reactflow.dev/src/pages/api-reference/hooks/use-nodes.mdx
- sites/reactflow.dev/src/references/hooks/useStore.ts
I've fixed several typos in the documentation. Thank you.
- uneccessarily, unecessarily -> unnecessarily
- unecessary -> unnecessary
- zustand/shaddlow -> zustand/shallow
> Fix several typos in the docs.

- sites/reactflow.dev/src/pages/learn/advanced-use/devtools-and-debugging.mdx
The link to 'use-nodes' in the document was incorrect and has now been corrected.
Thank you for checking.
> Fix a wrong link in the devtools-and-debugging docs.

- sites/reactflow.dev/src/pages/learn/tutorials/slide-shows-with-react-flow.mdx
Hello! Thanks for this wonderful library! I'm enjoying working through your tutorials.
The slideshow tutorial installation instructions use the reactflow package, but the code examples look like they want @xyflow/react. It didn't work for me as written, but was simple to figure out with either package.
I hope this is sufficient. Please let me know if you have any questions. Thanks again!
> Slideshow tutorial: update package install and references to reactflow for consistency.

- sites/reactflow.dev/src/pages/learn/index.mdx
Was trying out the demo, noticed that these two lines are not needed in the demo code, and is actually causing the code to break when running locally on a new install (when following the steps given earlier in the page)
> chore: remove code breaking demo

- sites/reactflow.dev/src/global.css
Closes #354 
Fix pulled from this issue: 
https://github.com/shadcn-ui/ui/issues/4227
It seems  like this is a common problem. Wanted to have it reviewed in case I'm not considering potential blowback from this css.
> fix(pricing-table): css override for scroll locked select component

- sites/reactflow.dev/src/pages/learn/tutorials/slide-shows-with-react-flow.mdx
This PR fixes a syntax error in the slide-shows-with-react-flow.mdx file. 
The file contained two 'export default' statements, which is invalid JavaScript syntax.
Changes made:
- Removed the redundant 'export default' statement.
This fix ensures that the tutorial code compiles correctly and prevents confusion for readers.
> Fix duplicate 'export default' in slide-shows tutorial

- sites/svelteflow.dev/src/pages/api-reference/components/edge-label-renderer.mdx
Copying this example into an editor just broke. I changed the imports and react-style className declaration.
> Fixed edge-label-renderer example syntax (svelte)

- apps/example-apps/svelte/examples/interaction/drag-and-drop/Flow.svelte
hello, going through the examples at the moment and noticed a small error in the drag and drop example:
https://svelteflow.dev/examples/interaction/drag-and-drop
if you drag and drop a node it will be called [object Object] node, because the label you assign is a store. I just added the $ prefix to deref the store:
> deref svelte store by adding $ prefix

- sites/reactflow.dev/src/pages/components/nodes/node-header.mdx
The link to `<BaseNode>` on the [Node Header](https://reactflow.dev/components/nodes/node-header) documentation page links to https://reactflow.dev/components/base-node and not https://reactflow.dev/components/nodes/base-node.
> Fix broken link to BaseNode in node-header.mdx

- apps/example-apps/svelte/examples/misc/threlte-flow/ThrelteScene.svelte
`useFrame()` takes a callback that expects the time elapsed in seconds to be the second param.
https://github.com/grischaerbe/threlte/blob/9e5a30f7bddbc000907f032734923106d2a6bf56/packages/core/src/lib/hooks/useFrame.ts#L25
> Fix ThrelteFlow example

- sites/reactflow.dev/src/pages/learn/advanced-use/computing-flows.mdx
it's not related to this code block?  we wrote getStaticProps in https://github.com/dimaMachina/web/blob/a642195e1aeb5c36fb136076a2d647ef92b9fad7/sites/reactflow.dev/src/pages/learn/advanced-use/computing-flows.mdx?plain=1#L10-L19
> Remove misplaced `getStaticProps/getStaticCode`

- packages/xy-shared/components/fathom.tsx
> load `<Fathom />` only on prod

- packages/xy-shared/layouts/base.tsx
- packages/xy-shared/layouts/blog-post-base.tsx
- packages/xy-shared/widgets/getting-started/index.tsx
- packages/xy-shared/widgets/hero-flow/index.tsx
- packages/xy-shared/widgets/hero/index.tsx
- packages/xy-ui/components/ui/footer/index.tsx
- packages/xy-ui/components/ui/heading.tsx
- packages/xy-ui/components/ui/section.tsx
- sites/reactflow.dev/src/app/(content-pages)/page.tsx
- sites/reactflow.dev/src/app/pro/examples/page.tsx
Widths of sections on the homepage should vertically align. I updated these values to all use the `--nextra-content-width` variable. Looks okay to me on the three sites but a second set of eyes would be good. 
* Headings should be `h2` unless main title of page
> chore: fix width of homepage sections

- sites/reactflow.dev/src/content/api-reference/components/controls.mdx
- sites/svelteflow.dev/src/content/api-reference/components/controls.mdx
`@xyflow/react` has `ControlProps` but `@xyflow/svelte` `ControlsProps`
https://github.com/xyflow/xyflow/blob/c4adfcfa8a21197858e44be41f7d231c654004fe/packages/react/src/additional-components/Controls/types.ts#L9
https://github.com/xyflow/xyflow/blob/c4adfcfa8a21197858e44be41f7d231c654004fe/packages/svelte/src/lib/plugins/Controls/types.ts#L6
> fix `ControlsProps` typo

- sites/reactflow.dev/src/content/learn/advanced-use/typescript.mdx
Noticed a minor typo in demo code here: https://reactflow.dev/learn/advanced-use/typescript
> Fix minor typo in `TypeScript` docs

- sites/reactflow.dev/src/content/learn/advanced-use/testing.mdx
Taking from [this comment ](https://github.com/xyflow/xyflow/issues/2461#issuecomment-2163004273), It is a good idea to include `panOnDrag={false}` in the testing documentation
> Chore: Update testing.mdx to include setting panOnDrag=false to disable d3-drag

- apps/example-apps/svelte/examples/edges/custom-edges/ButtonEdge.svelte
I migrated my custom edge to the `EdgeLabel` API and encountered a weird white dot.
Looking at the sample on the website I originally copied my component from, I found it to suffer from the same issue, with a lesser visual impact due to the low contrast between the background and the color of the dot.
According to the [migration guide](https://svelteflow.dev/learn/troubleshooting/migrate-to-v1#edgelabelrenderer-becomes-edgelabel-), I was using the `EdgeLabel` component incorrectly.
This PR syncs said example with the https://github.com/xyflow/web/blob/main/apps/example-apps/svelte/guides/concepts/ButtonEdge.svelte component which seems to have been migrated correctly.
> Fix Svelte/CustomEdge EdgeLabel usage

- sites/reactflow.dev/src/content/learn/concepts/terms-and-definitions.mdx
Some links in the docs were hardcoded to localhost. This PR updates them to the correct URLs.
> Fix documentation links pointing to localhost

- sites/svelteflow.dev/src/content/learn/index.mdx
Fixes a typo where the quickstart graph width is set to 100vh; this changes it to 100vw
> fix Svelte Flow quickstart graph fullscreening

- apps/example-apps/react/examples/nodes/delete-middle-node/App.jsx
- apps/example-apps/svelte/examples/nodes/delete-middle-node/App.svelte
Looks like delete middle node wasn't implemented in Svelte either.
> feat(delete-middle-node): allow multiple nodes to be deleted

- apps/example-apps/react/examples/edges/markers/App.tsx
- apps/example-apps/react/examples/edges/markers/CustomEdge.tsx
- apps/example-apps/react/examples/edges/markers/README.mdx
- apps/example-apps/react/examples/edges/markers/index.css
- apps/example-apps/react/examples/edges/markers/index.tsx
Related to https://github.com/xyflow/xyflow/issues/5441
> update markers example with color changing on selection

- apps/ui-components/registry/components/node-status-indicator/index.tsx
I thought I had more css fixes, but I could only remember this one, the border radius on the node status indicator spinner was off, so I adjusted it. 
I was tempted to remove the background color on this panel too, but maybe you all put it in intentionally?
> style(node-status-indicator): fix border radius on indicator
