pnpm-lock.yaml
sites/reactflow.dev/package.json
sites/reactflow.dev/src/pages/_meta.json
sites/reactflow.dev/src/pages/whats-new.mdx
sites/reactflow.dev/src/pages/whats-new/2023-11-01.mdx
sites/reactflow.dev/src/pages/whats-new/2023-11-02.mdx
sites/reactflow.dev/src/sites/whats-new.tsx
sites/reactflow.dev/src/utils/get-static-props/mdx-content-under-route.ts
sites/reactflow.dev/src/utils/routes.ts

https://github.com/xyflow/web/assets/9001354/3bbdc5d1-2457-4ada-bfbf-ffd5d787e956
Closes #183

✨ Create a "What's new" feed for docs changes.

---

apps/svelte-examples/src/routes/examples/nodes/update-node/+page.svelte
sites/svelteflow.dev/src/components/example-viewer/iframe-preview.tsx
sites/svelteflow.dev/src/components/example-viewer/index.tsx
sites/svelteflow.dev/src/components/example-viewer/setup.ts
sites/svelteflow.dev/src/pages/examples/layout/dagre.mdx
sites/svelteflow.dev/src/pages/examples/misc/threlte-flow.mdx
sites/svelteflow.dev/src/pages/examples/styling/tailwind.mdx
sites/svelteflow.dev/src/pages/examples/styling/turbo-flow.mdx

Fixed Stackblitz links & some examples

---

.github/ISSUE_TEMPLATE/submit-showcase.yaml
packages/xy-ui/components/layout/showcase.tsx

Created to guide folks through submitting their own projects to the React Flow / Svelte Flow showcase

feat(showcase): Add an issue template for submitting projects to the showcase

---

apps/svelte-examples/src/routes/examples/edges/custom-edges/BiDirectionalNode.svelte
apps/svelte-examples/src/routes/examples/edges/simple-floating-edges/CustomNode.svelte
apps/svelte-examples/src/routes/examples/feature-overview/CustomNode.svelte
apps/svelte-examples/src/routes/examples/interaction/contextual-zoom/ZoomNode.svelte
apps/svelte-examples/src/routes/examples/misc/hero-flow/ColorPickerNode.svelte
apps/svelte-examples/src/routes/examples/misc/hero-flow/SliderNode.svelte
apps/svelte-examples/src/routes/examples/misc/hero-flow/SwitcherNode.svelte
apps/svelte-examples/src/routes/examples/misc/hero-flow/ThrelteNode.svelte
apps/svelte-examples/src/routes/examples/nodes/connection-limit/CustomNode.svelte
apps/svelte-examples/src/routes/examples/nodes/custom-node/ColorSelectorNode.svelte
apps/svelte-examples/src/routes/examples/nodes/drag-handle/DragHandleNode.svelte
apps/svelte-examples/src/routes/examples/styling/tailwind/CustomNode.svelte
apps/svelte-examples/src/routes/examples/styling/turbo-flow/TurboNode.svelte
apps/svelte-examples/src/routes/guides/custom-nodes/a/ColorPickerNode.svelte
apps/svelte-examples/src/routes/guides/custom-nodes/b/ColorPickerNode.svelte
sites/svelteflow.dev/src/pages/learn/guides/custom-nodes.mdx

 on:connect on:connectstart on:connectend

---

sites/reactflow.dev/src/sites/whats-new.tsx
sites/xyflow.com/src/sites/about.tsx

sneaking in an apostrophe fix in the Whats New page

Add braks to about us page, fix apostrophes on whats-new

---

sites/reactflow.dev/theme.config.tsx

Fixed buggy routes with pro

---

sites/svelteflow.dev/src/pages/api-reference/hooks/use-handle-connections.mdx

Small fix in docs, in section `useHandleConnections`

---

sites/svelteflow.dev/src/page-data/reference/components/Controls.ts

Property was renamed in 0.0.24

chore(svelte): doc: update controls properties

---

sites/svelteflow.dev/src/pages/learn/guides/theming.mdx

Replaced React with Svelte in L129.

Update theming.mdx: L129: s/React/Svelte/

---

sites/svelteflow.dev/src/pages/examples/misc/threlte-flow.mdx

Update threlte-flow.mdx: L11: removed extra 'the'

---

sites/reactflow.dev/src/pages/learn/advanced-use/_meta.json
sites/reactflow.dev/src/pages/learn/advanced-use/ssr-ssg-configuration.mdx

React Flow SSR guide

---

sites/reactflow.dev/src/components/example-viewer/api-flows/Devtools/ChangeLogger.tsx
sites/reactflow.dev/src/pages/learn/advanced-use/devtools-and-debugging.mdx

I thought this guide would be an opportunity to explain a little more about `useStore`/`useStoreApi`, `onNodesChange` etc and how each of these components work.

Expand devtools guide.

---

sites/reactflow.dev/src/pages/learn/troubleshooting/migrate-to-v12.mdx

Fixed a typo

---

apps/svelte-examples/package.json
apps/svelte-examples/src/routes/examples/nodes/add-node-on-drop/Flow.svelte
pnpm-lock.yaml
sites/reactflow.dev/src/components/example-viewer/example-flows/AddNodeOnEdgeDrop/index.jsx

fix(edge-drop-example): work on touch devices

---

sites/reactflow.dev/src/pages/api-reference/hooks/use-handle-connections.mdx
sites/reactflow.dev/src/pages/api-reference/hooks/use-nodes-data.mdx

link to the hook was not correct

Update use-handle-connections.mdx Incorrect link

---

sites/reactflow.dev/src/pages/api-reference/utils/get-connected-edges.mdx

docs(getConnectedEdges): fix typo

---

sites/reactflow.dev/src/pages/api-reference/hooks/_meta.tsx
sites/reactflow.dev/src/pages/api-reference/hooks/use-handle-connections.mdx
sites/reactflow.dev/src/pages/api-reference/hooks/use-node-connections.mdx
sites/reactflow.dev/src/pages/api-reference/types/_meta.tsx
sites/reactflow.dev/src/pages/api-reference/types/node-connection.mdx
sites/reactflow.dev/src/references/hooks/useNodeConnections.ts
sites/reactflow.dev/src/references/types/NodeConnection.fields.ts
sites/reactflow.dev/src/references/types/ReactFlowInstance.fields.ts
sites/svelteflow.dev/src/pages/api-reference/hooks/_meta.tsx
sites/svelteflow.dev/src/pages/api-reference/hooks/use-handle-connections.mdx
sites/svelteflow.dev/src/pages/api-reference/hooks/use-node-connections.mdx
sites/svelteflow.dev/src/pages/api-reference/types/_meta.tsx
sites/svelteflow.dev/src/pages/api-reference/types/node-connection.mdx
sites/svelteflow.dev/src/references/hooks/useNodeConnections.ts
sites/svelteflow.dev/src/references/types/NodeConnection.fields.ts

Related to https://github.com/xyflow/xyflow/pull/4725

document useNodeConnections

---

README.md

Update README.md for typo issue

---

packages/xy-shared/server/toc.tsx
sites/reactflow.dev/src/app/(content-pages)/layout.tsx
sites/reactflow.dev/src/app/_meta.global.ts

soft-launch playground app

---

sites/reactflow.dev/src/content/learn/troubleshooting/migrate-to-v12.mdx

Fix typo in migrate-to-v12.mdx

---

sites/reactflow.dev/src/content/learn/advanced-use/accessibility.mdx

Here are some updates to the accessibility page to describe the new features and potential pitfalls. I also went through and tried to beef up the existing content to be a little more detailed. Would you mind taking a look?
@omesome this is from my current pitch but I think also fits into this learn pitch

docs(accessibility): update page with new features

---

sites/reactflow.dev/src/content/learn/customization/edge-labels.mdx

fix #945 React Flow example code error

docs: #945 update edge-labels.mdx

---

packages/xy-shared/widgets/hero-flow/flow.tsx

Fix 844 Flow is not fitted correctly when page is not focused

---

packages/xy-shared/server/utils.ts

https://github.com/xyflow/web/blob/main/sites/reactflow.dev/public/img/showcase/placeholder.jpg
https://github.com/xyflow/web/blob/main/sites/svelteflow.dev/public/img/showcase/placeholder.jpg

Change wrong showcase image format from PNG to JPG

---

sites/reactflow.dev/src/content/api-reference/components/control-button.mdx

Fix GitHub source link in `<ControlButton />` reference.

---

sites/svelteflow.dev/src/content/whats-new/2025-09-17.mdx

Added changelog for Svelte Flow version 1.3.0, detailing minor and patch changes.

Add changelog for Svelte Flow 1.3.0

---

packages/xy-shared/server/remote-code-viewer/index.tsx

Part of https://github.com/xyflow/web/issues/1015

Disable Open in CodeSandbox  Button
